package com.schemalens.app.cicd

import com.schemalens.app.data.Dialect

/**
 * Automated Git Pre-Commit CI/CD Hook Generator.
 *
 * Generates shell scripts (.pre-commit) that run SchemaLens's static AST regex scanner
 * in headless mode before any developer runs `git commit`. If a schema change alters
 * a column without an updated migration file, the commit is blocked locally.
 *
 * Supports both Bash (Linux/Mac) and PowerShell (Windows) variants.
 * Elevates SchemaLens into an enterprise-ready security gate.
 */
object GitHookGenerator {

    enum class ShellType(val label: String, val extension: String) {
        BASH("Bash (Linux/Mac)", ".sh"),
        POWERSHELL("PowerShell (Windows)", ".ps1")
    }

    /**
     * Generates a pre-commit hook script that scans staged files for
     * schema-altering keywords and blocks commits with unprotected changes.
     *
     * @param protectedColumns List of column names marked as protected in schema policy
     * @param dialect The target ORM dialect for context-aware scanning
     * @param shellType The shell variant to generate for
     */
    fun generatePreCommitHook(
        protectedColumns: List<String>,
        dialect: Dialect,
        shellType: ShellType = ShellType.BASH
    ): String {
        return when (shellType) {
            ShellType.BASH -> generateBashHook(protectedColumns, dialect)
            ShellType.POWERSHELL -> generatePowerShellHook(protectedColumns, dialect)
        }
    }

    private fun generateBashHook(
        protectedColumns: List<String>,
        dialect: Dialect
    ): String {
        val filePatterns = when (dialect) {
            Dialect.DRIZZLE -> "*.ts *.js"
            Dialect.ANDROID_ROOM -> "*.kt *.java"
            Dialect.PRISMA -> "*.prisma"
            Dialect.RAW_SQL -> "*.sql"
        }

        val protectedList = protectedColumns.joinToString(" ") { "\"$it\"" }

        return """
#!/bin/bash
# ============================================================
# SchemaLens Pre-Commit Hook v2.0
# Generated by SchemaLens Studio — On-Device SLM · Air-Gapped
# ============================================================
# Install: cp this file to .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
# Target Dialect: ${dialect.displayName}
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
BOLD='\033[1m'

echo ""
echo -e "${'$'}{BOLD}🛡️  SchemaLens Pre-Commit Safety Gate${'$'}{NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Protected column names from .schemalens-policy.json
PROTECTED_COLUMNS=($protectedList)

# Schema-altering keywords that trigger inspection
DANGER_KEYWORDS="DROP\s+COLUMN|ALTER\s+TABLE|RENAME\s+COLUMN|DROP\s+TABLE|MODIFY\s+COLUMN|CHANGE\s+COLUMN"

# Get staged files matching the dialect pattern
STAGED_FILES=${'$'}(git diff --cached --name-only --diff-filter=ACM -- $filePatterns 2>/dev/null || true)

if [ -z "${'$'}STAGED_FILES" ]; then
    echo -e "${'$'}{GREEN}✓ No schema files staged. Commit allowed.${'$'}{NC}"
    exit 0
fi

VIOLATIONS=0
VIOLATION_LOG=""

for FILE in ${'$'}STAGED_FILES; do
    echo -e "  Scanning: ${'$'}{YELLOW}${'$'}FILE${'$'}{NC}"
    
    # Check for schema-altering keywords
    MATCHES=${'$'}(grep -nEi "${'$'}DANGER_KEYWORDS" "${'$'}FILE" 2>/dev/null || true)
    
    if [ -n "${'$'}MATCHES" ]; then
        while IFS= read -r line; do
            LINE_NUM=${'$'}(echo "${'$'}line" | cut -d: -f1)
            LINE_TEXT=${'$'}(echo "${'$'}line" | cut -d: -f2-)
            
            # Check if any protected column is referenced
            for COL in "${'$'}{PROTECTED_COLUMNS[@]}"; do
                if echo "${'$'}LINE_TEXT" | grep -qi "${'$'}COL"; then
                    VIOLATIONS=${'$'}((VIOLATIONS + 1))
                    VIOLATION_LOG+="  ${'$'}{RED}✗ BREAKING${'$'}{NC} ${'$'}FILE:${'$'}LINE_NUM — ${'$'}LINE_TEXT\n"
                    VIOLATION_LOG+="    Protected column '${'$'}COL' is being altered without a migration.\n"
                fi
            done
        done <<< "${'$'}MATCHES"
    fi
done

echo ""
if [ ${'$'}VIOLATIONS -gt 0 ]; then
    echo -e "${'$'}{RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${'$'}{NC}"
    echo -e "${'$'}{RED}${'$'}{BOLD}✗ COMMIT BLOCKED — ${'$'}VIOLATIONS schema violation(s) detected${'$'}{NC}"
    echo -e "${'$'}{RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${'$'}{NC}"
    echo ""
    echo -e "${'$'}VIOLATION_LOG"
    echo ""
    echo -e "${'$'}{YELLOW}To proceed, either:"
    echo "  1. Add a corresponding migration file"
    echo "  2. Update .schemalens-policy.json to unprotect the column"
    echo -e "  3. Use --no-verify to bypass (not recommended)${'$'}{NC}"
    exit 1
else
    echo -e "${'$'}{GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${'$'}{NC}"
    echo -e "${'$'}{GREEN}${'$'}{BOLD}✓ All schema changes verified. Commit allowed.${'$'}{NC}"
    echo -e "${'$'}{GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${'$'}{NC}"
    exit 0
fi
""".trimIndent()
    }

    private fun generatePowerShellHook(
        protectedColumns: List<String>,
        dialect: Dialect
    ): String {
        val filePatterns = when (dialect) {
            Dialect.DRIZZLE -> "*.ts,*.js"
            Dialect.ANDROID_ROOM -> "*.kt,*.java"
            Dialect.PRISMA -> "*.prisma"
            Dialect.RAW_SQL -> "*.sql"
        }

        val protectedList = protectedColumns.joinToString(", ") { "\"$it\"" }

        return """
# ============================================================
# SchemaLens Pre-Commit Hook v2.0 (PowerShell)
# Generated by SchemaLens Studio — On-Device SLM · Air-Gapped
# ============================================================
# Install: Save as .git/hooks/pre-commit.ps1
# Target Dialect: ${dialect.displayName}
# ============================================================

${'$'}ProtectedColumns = @($protectedList)
${'$'}DangerPattern = "DROP\s+COLUMN|ALTER\s+TABLE|RENAME\s+COLUMN|DROP\s+TABLE|MODIFY\s+COLUMN|CHANGE\s+COLUMN"

Write-Host ""
Write-Host "🛡️  SchemaLens Pre-Commit Safety Gate" -ForegroundColor Cyan -NoNewline
Write-Host " (PowerShell)" -ForegroundColor DarkGray
Write-Host ("━" * 40) -ForegroundColor DarkGray

${'$'}StagedFiles = git diff --cached --name-only --diff-filter=ACM -- $filePatterns 2>${'$'}null
${'$'}Violations = 0

if (-not ${'$'}StagedFiles) {
    Write-Host "✓ No schema files staged. Commit allowed." -ForegroundColor Green
    exit 0
}

foreach (${'$'}File in ${'$'}StagedFiles) {
    Write-Host "  Scanning: ${'$'}File" -ForegroundColor Yellow
    ${'$'}Content = Get-Content ${'$'}File -ErrorAction SilentlyContinue
    ${'$'}LineNum = 0

    foreach (${'$'}Line in ${'$'}Content) {
        ${'$'}LineNum++
        if (${'$'}Line -match ${'$'}DangerPattern) {
            foreach (${'$'}Col in ${'$'}ProtectedColumns) {
                if (${'$'}Line -match ${'$'}Col) {
                    ${'$'}Violations++
                    Write-Host "  ✗ BREAKING ${'$'}File:${'$'}LineNum — ${'$'}(${'$'}Line.Trim())" -ForegroundColor Red
                    Write-Host "    Protected column '${'$'}Col' is being altered." -ForegroundColor DarkRed
                }
            }
        }
    }
}

Write-Host ""
if (${'$'}Violations -gt 0) {
    Write-Host ("━" * 40) -ForegroundColor Red
    Write-Host "✗ COMMIT BLOCKED — ${'$'}Violations schema violation(s) detected" -ForegroundColor Red
    Write-Host ("━" * 40) -ForegroundColor Red
    Write-Host ""
    Write-Host "To proceed, either:" -ForegroundColor Yellow
    Write-Host "  1. Add a corresponding migration file" -ForegroundColor Yellow
    Write-Host "  2. Update .schemalens-policy.json to unprotect the column" -ForegroundColor Yellow
    Write-Host "  3. Use --no-verify to bypass (not recommended)" -ForegroundColor Yellow
    exit 1
} else {
    Write-Host ("━" * 40) -ForegroundColor Green
    Write-Host "✓ All schema changes verified. Commit allowed." -ForegroundColor Green
    Write-Host ("━" * 40) -ForegroundColor Green
    exit 0
}
""".trimIndent()
    }

    /**
     * Generates a .schemalens-policy.json template listing protected columns.
     */
    fun generatePolicyTemplate(protectedColumns: List<String>): String {
        val colEntries = protectedColumns.joinToString(",\n        ") { "\"$it\"" }
        return """
{
    "schemalens_version": "2.0.0",
    "policy": {
        "protected_columns": [
            $colEntries
        ],
        "require_migration_for": [
            "DROP COLUMN",
            "RENAME COLUMN",
            "ALTER TABLE",
            "DROP TABLE"
        ],
        "auto_block_commit": true,
        "notification": {
            "slack_webhook": null,
            "email": null
        }
    }
}
""".trimIndent()
    }

    /**
     * Extracts column names from the current schema DDL to pre-populate the policy template.
     */
    fun extractColumnsFromDdl(schemaDdl: String): List<String> {
        val columns = mutableListOf<String>()
        val columnRegex = Regex("""(\w+)\s+(VARCHAR|INTEGER|TEXT|BOOLEAN|TIMESTAMP|SERIAL|UUID|BIGINT|DECIMAL|FLOAT|DATE|INT|REAL)""", RegexOption.IGNORE_CASE)

        for (match in columnRegex.findAll(schemaDdl)) {
            val colName = match.groupValues[1]
            // Filter out SQL keywords that look like column names
            if (colName.lowercase() !in setOf("create", "table", "not", "primary", "foreign", "key", "default", "unique", "index")) {
                columns.add(colName)
            }
        }
        return columns.distinct()
    }
}
